name: Azure Deploy

on:
  push:
    branches:
      - main
    paths:
      - infra/**
  pull_request:
    branches: 
      - main
    paths:
      - infra/**
  workflow_dispatch: # manual trigger

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Create Resource Group
        uses: Azure/CLI@v2
        with:
          inlineScript: |
            az group create --name ${{ vars.RESOURCE_GROUP_NAME }} --location ${{ vars.RESOURCE_GROUP_LOCATION }}
            echo "Azure resource group created"
      - name: Deploy Infrastructure
        uses: azure/arm-deploy@v2
        with:
          resourceGroupName: ${{ vars.RESOURCE_GROUP_NAME }}
          template: ./infra/main.bicep
          parameters: environment=dev
      - name: Logout from Azure
        run: az logout
        if: always()

  deploy-stg:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: Staging
    steps:
      - uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Create Resource Group
        uses: Azure/CLI@v2
        with:
          inlineScript: |
            az group create --name ${{ vars.RESOURCE_GROUP_NAME }} --location ${{ vars.RESOURCE_GROUP_LOCATION }}
            echo "Azure resource group created"
      - name: Deploy Infrastructure
        uses: azure/arm-deploy@v2
        with:
          resourceGroupName: ${{ vars.RESOURCE_GROUP_NAME }}
          template: ./infra/main.bicep
          parameters: environment=stg
      - name: Logout from Azure
        run: az logout
        if: always()

  deploy-prd:
    runs-on: ubuntu-latest
    needs: deploy-stg
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: Production
    steps:
      - uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Create Resource Group
        uses: Azure/CLI@v2
        with:
          inlineScript: |
            az group create --name ${{ vars.RESOURCE_GROUP_NAME }} --location ${{ vars.RESOURCE_GROUP_LOCATION }}
            echo "Azure resource group created"
      - name: Deploy Infrastructure
        uses: azure/arm-deploy@v2
        with:
          resourceGroupName: ${{ vars.RESOURCE_GROUP_NAME }}
          template: ./infra/main.bicep
          parameters: environment=prd
      - name: Logout from Azure
        run: az logout
        if: always()